server:
  port: 8082

mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: root12345
  dbName: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 28
  compress: true
